---
- name: Restart sssd service
  hosts: all
  tasks:
    - name: Restart service sssd
      service:
        name: sssd
        state: restarted
    - name: Check status of service sssd
      shell: service sssd status
